### ISSUE TITLE
External axis moving extremely slow when using EGM & multimove

### ISSUE THREAD

**Issue by Jakey9** [PickNikRobotics/abb_ros2#84]
I am trying to move a irb6620 on external linear rail. i successfully set up ros2 to stream joint values to control a virtual controller inside robotstudio.
However, I am unable to control the speed of the arm and the linear rail. Arm speed is acceptable but linear rail is extremely slow. 
I used wireshark to to see the frequency rates of data packet coming in and it seems ok, but the incremental step is very little.

**Things I have tried:**

**Adjusting velocity and acceleration limits in joint_limits.yaml:**
```
default_velocity_scaling_factor: 1.0  #tried this but doesnt work
default_acceleration_scaling_factor: 1.0  #tried this but doesnt work

joint_limits:
  rob3_joint_2:
    has_velocity_limits: true  
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
  rob3_joint_3:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
  rob3_joint_4:
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: false
    max_acceleration: 0
  rob3_joint_5:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: false
    max_acceleration: 0
  rob3_joint_6:
    has_velocity_limits: true
    max_velocity: 3.32
    has_acceleration_limits: false
    max_acceleration: 0
  rob3_track:
    has_velocity_limits: true
    max_velocity: 10.0  #tried this but doesn't work (1, 10, 500, etc)
    has_acceleration_limits: false #tried this but doesnt work
    max_acceleration: 0 #tried this but doesnt work
```

**adjusting rates in robot_controllers.yaml:**
```
/robot3/controller_manager:
  ros__parameters:
    update_rate: 250  # Hz   #tried this but doesnt work

    rob3_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rob3_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    rob3_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/robot3/rob3_joint_trajectory_controller:
  ros__parameters:
    joints:
      - rob3_joint_1
      - rob3_joint_2
      - rob3_joint_3
      - rob3_joint_4
      - rob3_joint_5
      - rob3_joint_6
      - rob3_track
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 250.0    #tried this but doesnt work
    action_monitor_rate: 50.0   #tried this but doesnt work
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 3.0
```

**robotstudio rapid program:**

```
MODULE TExtAxisMain

    !***********************************************************
    ! Program data
    !***********************************************************
    ! Home position.
    VAR jointtarget jt;
    PERS speeddata speed := [0, 0, 200, 0];   

    ! Identifier for the EGM correction.
    LOCAL VAR egmident egm_id;

    ! Limits for convergance.
    LOCAL VAR egm_minmax egm_condition := [-0.1, 0.1];

    PROC main()
        jt.extax := [0, 0, 0, 0, 0, 0];   
        MoveExtJ jt, speed, fine;
        
        ! Register an EGM id.
        EGMGetId egm_id;

        ! Setup the EGM communication.
        EGMSetupUC IRT510_IRB_DBL2_INT, egm_id, "default", "EXTAX", \Joint;

        ! Prepare for an EGM communication session.
        EGMActJoint egm_id;

        WHILE TRUE DO
            ! Start the EGM communication session.
            ! EGMRunJoint egm_id, EGM_STOP_HOLD, \CondTime:=5 \RampOutTime:=5 \PosCorrGain:=0;
            EGMRunJoint egm_id, EGM_STOP_HOLD;
        ENDWHILE
        ! Release the EGM id.
        EGMReset egm_id;


    ERROR
        IF ERRNO = ERR_UDPUC_COMM THEN
            TPWrite "Communication timedout";
            TRYNEXT;
        ENDIF
    ENDPROC
ENDMODULE
```

How can I fix / control robot velocity, especially the external axis? 

Also, when starting ros2 control launch, the robot always go into 0,0,0,0,0,0 position. how can I prevent that?
